// <auto-generated />
namespace DWD278_FinalProject_VH.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TypeStatus : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TypeStatus));
        
        string IMigrationMetadata.Id
        {
            get { return "201611071438045_TypeStatus"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
